name: Build Android APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Download Stable Zip
      run: |
        curl -L -o template.zip https://github.com/vimalcvs/Android-WebView-App-Template/archive/refs/heads/main.zip
        unzip template.zip
        DIR_NAME=$(ls -d */ | grep Android-WebView)
        mv "$DIR_NAME" template
        rm -rf template/app/src/main/assets/*
        cp -r * template/app/src/main/assets/ || true

    - name: Build APK with Gradle
      run: |
        cd template
        chmod +x gradlew
        ./gradlew assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: KrdOnlineTV-APK
        path: template/app/build/outputs/apk/debug/app-debug.apk
